# Generated by Django 5.0.6 on 2024-08-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=100)),
                ('twitch', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
    ]
